services:
  postgres:
    container_name: postgres_db_restaurant

    ports:
      - '5432:5432'

    image: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_restaurant
